name: Build and attach JAR to release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp -DskipTests package

      - name: Upload asset to release
        uses: Shopify/upload-to-release@c77c9b3e5d288adaef98a7007bf92340ec6ce03b
        with:
          name: BurpMCP.jar
          path: target/burpmcp-1.0-jar-with-dependencies.jar
          content-type: application/java-archive
          repo-token: ${{ secrets.GITHUB_TOKEN }}


