name: Build and attach JAR to release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp -DskipTests package

      - name: Rename JAR to BurpMCP.jar
        shell: bash
        run: |
          set -euo pipefail
          FILE=$(ls target/*-jar-with-dependencies.jar | head -n 1)
          cp "$FILE" target/BurpMCP.jar

      - name: Upload asset to release
        uses: softprops/action-gh-release@v0.2.1
        with:
          files: target/BurpMCP.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


